apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.30"

nodeGroups:
  - name: linux-nodes
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 3